version: "3.6"

services:
  challenge:
    build:
      context: ../../object_challenge
      dockerfile: Dockerfile
    image: challenge
    container_name: challenge
    networks:
      - backend
      - frontend
    dns:
      - 8.8.8.8
      - 4.2.2.4
    ports:
      - 5000:5000
    depends_on:
      - mongo
  openresty:
    build:
      context: ./openresty_lua
      dockerfile: Dockerfile
    image: openresty
    container_name: openresty
    restart: unless-stopped
    networks:
      - backend
      - frontend
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    depends_on:
      - mongo
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/lua:/etc/lua
  mongo:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    env_file:
      - env_dir/mongo.env
    networks:
      - backend
    dns:
      - 8.8.8.8
      - 4.2.2.4
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - mongo-data:/data/db

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  common-data:
    driver: local
  mongo-data:
    driver: local