version: "3.6"

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    env_file:
      - env_dir/mongo.env
    networks:
      - backend
    dns:
      - 8.8.8.8
      - 4.2.2.4
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - mongo-data:/data/db

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  common-data:
    driver: local
  mongo-data:
    driver: local