# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ci


on:
  push:
    branches: [ master ]

jobs:
  build:
    services:
      mongo:
        image: mongo
        env_file:
          - ../../deployment/env_dir/mongo.env
        ports:
          - 27017:27017
        volumes:
          - ../../deployment/data/mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements/stage.txt ]; then pip install -r requirements/stage.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=14 --max-line-length=120 --statistics
    - name: Test with pytest
      run: |
        python manage.py test